/** @type {import('next').NextConfig} */
const nextConfig = {
    experimental: {
        appDir: true,
        metadata: {
            title: 'Create Next App',
            description: 'Generated by create next app',
        },
        subsets: ['latin']
    }
}

module.exports = nextConfig
